<?php

$GLOBALS['paises'] = [
  'Brasil',
  'África do Sul',
    'Albânia',
    'Alemanha',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua',
    'Arábia Saudita',
    'Argentina',
    'Armênia',
    'Aruba',
    'Austrália',
    'Áustria',
    'Azerbaijão',
    'Bahamas',
    'Bahrein',
    'Bangladesh',
    'Barbados',
    'Bélgica',
    'Benin',
    'Bermudas',
    'Botsuana',
    'Brunei',
    'Bulgária',
    'Burkina Fasso',
    'Butão',
    'Cabo Verde',
    'Camarões',
    'Camboja',
    'Canadá',
    'Cazaquistão',
    'Chade',
    'Chile',
    'China',
    'Cidade do Vaticano',
    'Colômbia',
    'Congo',
    'Coréia do Sul',
    'Costa do Marfim',
    'Costa Rica',
    'Croácia',
    'Dinamarca',
    'Djibuti',
    'Dominica',
    'EUA',
    'Egito',
    'El Salvador',
    'Emirados Árabes',
    'Equador',
    'Eritréia',
    'Escócia',
    'Eslováquia',
    'Eslovênia',
    'Espanha',
    'Estônia',
    'Etiópia',
    'Fiji',
    'Filipinas',
    'Finlândia',
    'França',
    'Gabão',
    'Gâmbia',
    'Gana',
    'Geórgia',
    'Gibraltar',
    'Granada',
    'Grécia',
    'Guadalupe',
    'Guam',
    'Guatemala',
    'Guiana',
    'Guiana Francesa',
    'Guiné-bissau',
    'Haiti',
    'Holanda',
    'Hondura',
    'Hong Kong',
    'Hungria',
    'Iêmen',
    'Ilhas Cayman',
    'Ilhas Cook',
    'Ilhas Curaçao',
    'Ilhas Marshall',
    'Ilhas Turks & Caicos',
    'Ilhas Virgens (brit.)',
    'Ilhas Virgens(amer.)',
    'Ilhas Wallis e Futuna',
    'Índia',
    'Indonésia',
    'Irlanda',
    'Islândia',
    'Israel',
    'Itália',
    'Jamaica',
    'Japão',
    'Jordânia',
    'Kuwait',
    'Latvia',
    'Líbano',
    'Liechtenstein',
    'Lituânia',
    'Luxemburgo',
    'Macau',
    'Macedônia',
    'Madagascar',
    'Malásia',
    'Malaui',
    'Mali',
    'Malta',
    'Marrocos',
    'Martinica',
    'Mauritânia',
    'Mauritius',
    'México',
    'Moldova',
    'Mônaco',
    'Montserrat',
    'Nepal',
    'Nicarágua',
    'Niger',
    'Nigéria',
    'Noruega',
    'Nova Caledônia',
    'Nova Zelândia',
    'Omã',
    'Palau',
    'Panamá',
    'Papua-nova Guiné',
    'Paquistão',
    'Peru',
    'Polinésia Francesa',
    'Polônia',
    'Porto Rico',
    'Portugal',
    'Qatar',
    'Quênia',
    'Rep. Dominicana',
    'Rep. Tcheca',
    'Reunion',
    'Romênia',
    'Ruanda',
    'Rússia',
    'Saipan',
    'Samoa Americana',
    'Senegal',
    'Serra Leone',
    'Seychelles',
    'Singapura',
    'Síria',
    'Sri Lanka',
    'St. Kitts & Nevis',
    'St. Lúcia',
    'St. Vincent',
    'Sudão',
    'Suécia',
    'Suiça',
    'Suriname',
    'Tailândia',
    'Taiwan',
    'Tanzânia',
    'Togo',
    'Trinidad & Tobago',
    'Tunísia',
    'Turquia',
    'Ucrânia',
    'Uganda',
    'Uruguai',
    'Venezuela',
    'Vietnã',
    'Zaire',
    'Zâmbia',
    'Zimbábue'
];

$GLOBALS['areas_conhecimento'] = [
  'Ciências Exatas e da Terra', 
  'Ciências Biológicas', 
  'Engenharias', 
  'Ciências da Saúde', 
  'Ciências Agrárias', 
  'Ciências Sociais Aplicadas', 
  'Ciências Humanas',
  'Linguística', 
  'Letras e Artes', 
  'Pós Graduação', 
  'Outros'
];

$GLOBALS['escolaridade'] = [
'Ensino Fundamental',
'Ensino Médio',
'Ensino Técnico',
'Ensino Superior',
'Pós Graduação',
'Mestrado',
'Doutorado',
'Pós Doutorado',
];

$GLOBALS['tipo_instituicao'] = [
  'Pública',
  'Privada'
];

$GLOBALS['tamanho_empresa'] = [
  'Grande',
  'Média',
  'Pequena',
  'MEI',
  'Não se aplica'
];

$GLOBALS['p_institucional'] = [
  'Organização da Sociedade Civil',
  'Empresa',
  'Governo',
  'Instituições de Ensino e Pesquisa',
  'Instituições de Apoio'
];

$GLOBALS['ambientes'] = [
  'Não',
  'Biblioteca',
  'Coworking',
  'Grupo de Pesquisa',
  'Incubadora/Aceleradora/Hotel Tecnológico',
  'Laboratório',
  'NIT',
  'Observatório',
  'Parque Tecnológico',
  'Outros'
];